### PR TITLE
Spanish Translation added

### PR DESCRIPTION
**Pull request by PythonCoderUnicorn**
Added Spanish translation to the page

### CODE REVIEW

**Review by MichaelChirico — COMMENTED** [review]
Translation looks basically OK to me (as in, I don't see any immediate issue), though it should really be reviewed by a native speaker if possible.

At a higher level, how will this look in the end? Just as in the code, i.e., English/Spanish interwoven? Or will there be a toggle English :left_right_arrow: Spanish?

cc @PamelaPairo who may have insights on the best approach here, UX/UI-wise

**Comment by PythonCoderUnicorn** [comment]
Having a native Spanish speaker was always the goal but when this was the discussion no other person had time or was willing to do it. The  Spanish translation was to have a first pass, something there and to be inclusive. I would love it if all the Spanish Translations i worked on was taken over by a R Spanish speaker. 

As for Spanish code, I have no plans on that and is beyond my knowledge.

**Comment by MichaelChirico** [comment]
OK, thank you so much for taking the time & effort! It's definitely a boon to have a Spanish version of the README available.

I am still a bit torn about merging as is -- the alternative I have in mind is a README-es.md. The downside of the current PR is it makes the README a bit less readable for both English & Spanish speakers (who have to spend mental effort jumping around the page for "their" next section). And it will be quite tough for screen readers -- I may be wrong but I imagine most screen readers are not built to be bilingual and will butcher either the English or the Spanish pronunciation / make for a confusing experience overall.

The advantage of the current approach is it's more inclusive to put Spanish & English side-by-side as coequals, rather than make English the default and have some extra steps to see Spanish (of course all websites have a default, but typically the next language is just a click away -- I think it will be hard to replicate that UX here).

So I'd like a second opinion about how to move forward from here -- cc @hturner any idea?

**Comment by MichaelChirico** [comment]
Just saw that the same approach was taken over here:

https://github.com/forwards/rcontribution

So I'll take that as a nod to the current approach & merge for now.

We can always revisit later in consideration of the above.

Thanks again!

**Comment by hturner** [comment]
Just catching up here. I think it is works fine as a first improvement to making this resource more accessible. but I like the idea of having separate file as that raises the possibility of translating to other languages. To avoid English being the default, we can simply make the README a landing page, with links to the files for each language. I will raise an issue in case any wants to work on this!

**Pull request merged**
